[package]
name = "dir-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.7.0", default-features = false, features = ["v4"] }

[dev-dependencies]
tempdir = "0.3.7"